name: DEPLOY PROD
permissions:
  contents: write
on:
  push:
    tags:
      - "prod-v*"

jobs:
  deploy-prod:
    environment: prod
    name: IPFS Pinata deploy GitHub action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm install -g yarn

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build
          touch dist/.nojekyll
  
      - uses: popovoleksandr/ipfs-pinata-deploy-action@v1.6.3
        with:
          pin-name: 'Bootcamp'
          path: './dist'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET }}
          verbose: true
          remove-old: false
